### ISSUE TITLE
ergoConnector.nautilus.isConnected() returns Bool but should return Promise<Bool>

### ISSUE THREAD

**Issue by MrStahlfelge** [ThierryM1212/SAFEW#19]
As stated above. Nautilus' ergoConnector.nautilus.isConnected() returns a Promise<Bool>, while SAFEW's injection returns a Bool. This makes problems in client code because clients not prepared for Nautilus get exceptions.

**Comment by ThierryM1212** [comment]
Thanks for reporting the issue.
It is now fixed with the 0.6.6 being published currently.
