### ISSUE TITLE
Does not work with the latest Ledger build from Tesseract

### ISSUE THREAD

**Issue by squigglemiggles** [ThierryM1212/SAFEW#23]
The latest ledger build from tesseract broke the signing of tx's in safew.
It used to work fine but with the latest run it's no longer signing (https://github.com/tesseract-one/ledger-app-ergo/actions/runs/3613041599).

I guess the new ledger UI is to blame :)

**Comment by ThierryM1212** [comment]
Thanks for reporting it.
It will be fixed with the 0.6.9 coming soon.

(upgrade ledger-ergo-js from 0.1.1 to 0.1.14)
